
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Kelompok 1 - 15.2A.01
 */
public class Warung extends javax.swing.JFrame {

    
    Kasir ksr = new Kasir();

    /**
     * Creates new form warung
     */
    
    // constructor
    public Warung() {
        initComponents();

        // merupakan menu dari warung indomie
        tarea.setText(
                "Selamat datang di Warung Indomie Bersama\n\n"
                + "Kami menyediakan menu seperti di bawah ini:\n\n"
                + "Paket:\n"
                + "1. Paket 1: Indomie Original\n"
                + "   Harga: Rp 12.000\n\n"
                + "2. Paket 2: Indomie Telor\n"
                + "   Harga: Rp 15.000\n\n"
                + "3. Paket 3: Indomie Telor Kornet\n"
                + "   Harga: Rp 17.000\n\n"
                + "Minuman:\n"
                + "1. Air Mineral\n"
                + "   Harga: Rp 4.000\n\n"
                + "2. Es Teh Manis\n"
                + "   Harga: Rp 7.000\n\n"
                + "3. Es Kopi Susu\n"
                + "   Harga: Rp 8.000\n\n"
                + "Selamat menikmati hidangan kami!"
        );
//        r1.setSelected(true);

        tharjmlhmin.setText(Long.toString(ksr.getHargaMinuman("AIR MINERAL")));
        tharjmlhteh.setText(Long.toString(ksr.getHargaMinuman("ES TEH MANIS")));
        tharjmlhkopi.setText(Long.toString(ksr.getHargaMinuman("ES KOPI SUSU")));

        Bersih();
    }

    private void Bersih() {

        hargaLayanan.setEnabled(false);
        cmakanan.setSelectedIndex(0);
        jmineral.setSelected(false);
        jmineral.setSelected(false);
        jteh.setSelected(false);
        jkopi.setSelected(false);
        tjummineral.setText("");
        tjumteh.setText("");
        tjumkosu.setText("");
        totharga.setText("");
        ttminuman.setText("");
        totubay.setText("");
        totukem.setText("");
        ksr.setJumlahBeliJenisMinuman(0, "");
        ksr.setPaket("");
        comboLayanan.setSelectedIndex(0);
        ksr.setLayananPembayaran("");
        ksr.resetTotalPembayaran();
        hargaLayanan.setText("");
        /**
         * Panel Makanan
         */
        tnamamakanan.setEnabled(false);
        thargamakan.setEnabled(false);
        ttmakanan.setEnabled(false);
        bhitungtotmakanan.setEnabled(false);
        tbelimakanan.setEnabled(false);

        /**
         * Panel Minuman
         */
        tharjmlhmin.setEnabled(false);
        tharjmlhteh.setEnabled(false);
        tharjmlhkopi.setEnabled(false);
        tjummineral.setEnabled(false);
        tjumteh.setEnabled(false);
        tjumkosu.setEnabled(false);
        ttminuman.setEnabled(false);
        bhitungtotminuman.setEnabled(false);

        totharga.setEnabled(false);
        totukem.setEnabled(false);
        totubay.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelMenu = new javax.swing.JPanel();
        cmakanan = new javax.swing.JComboBox<>();
        thargamakan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tnamamakanan = new javax.swing.JTextField();
        tbelimakanan = new javax.swing.JTextField();
        ttmakanan = new javax.swing.JTextField();
        bhitungtotmakanan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jmineral = new javax.swing.JCheckBox();
        jteh = new javax.swing.JCheckBox();
        jkopi = new javax.swing.JCheckBox();
        tjummineral = new javax.swing.JTextField();
        tjumteh = new javax.swing.JTextField();
        tjumkosu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ttminuman = new javax.swing.JTextField();
        bhitungtotminuman = new javax.swing.JButton();
        tharjmlhmin = new javax.swing.JTextField();
        tharjmlhteh = new javax.swing.JTextField();
        tharjmlhkopi = new javax.swing.JTextField();
        panelDelivery = new javax.swing.JPanel();
        comboLayanan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarea = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        hargaLayanan = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        totharga = new javax.swing.JTextField();
        bbersih = new javax.swing.JButton();
        bselesai = new javax.swing.JButton();
        totubay = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        totukem = new javax.swing.JTextField();
        btotal = new javax.swing.JButton();
        bubay = new javax.swing.JButton();
        bgrnn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelMenu.setBackground(new java.awt.Color(204, 204, 204));

        cmakanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH MENU MAKANAN", "PAKET 1", "PAKET 2", "PAKET 3" }));
        cmakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmakananActionPerformed(evt);
            }
        });

        jLabel1.setText("NAMA MAKANAN");

        jLabel2.setText("HARGA");

        jLabel3.setText(" JUMLAH BELI");

        jLabel4.setText("TOTAL HARGA MAKANAN");

        tbelimakanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbelimakananKeyReleased(evt);
            }
        });

        bhitungtotmakanan.setText("HITUNG TOTAL HARGA MAKANAN");
        bhitungtotmakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungtotmakananActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(261, 236));

        jLabel13.setText("MINUMAN");

        jLabel14.setText("HARGA");

        jLabel19.setText("JUMLAH BELI");

        jmineral.setText("AIR MINERAL");
        jmineral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmineralActionPerformed(evt);
            }
        });

        jteh.setText("ES TEH MANIS");
        jteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtehActionPerformed(evt);
            }
        });

        jkopi.setText("ES KOPI SUSU");
        jkopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkopiActionPerformed(evt);
            }
        });

        tjummineral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tjummineralKeyReleased(evt);
            }
        });

        tjumteh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tjumtehKeyReleased(evt);
            }
        });

        tjumkosu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tjumkosuKeyReleased(evt);
            }
        });

        jLabel8.setText("TOTAL  HARGA MINUMAN");

        bhitungtotminuman.setText("HITUNG TOTAL HARGA MINUMAN");
        bhitungtotminuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungtotminumanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jmineral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jteh)
                            .addComponent(jkopi, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tharjmlhkopi, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(tharjmlhteh)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14))
                    .addComponent(tharjmlhmin))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tjumkosu, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(tjumteh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tjummineral, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ttminuman))
                    .addComponent(bhitungtotminuman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmineral)
                    .addComponent(tjummineral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tharjmlhmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jteh)
                    .addComponent(tjumteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tharjmlhteh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jkopi)
                    .addComponent(tjumkosu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tharjmlhkopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttminuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bhitungtotminuman)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmakanan, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tnamamakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thargamakan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbelimakanan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ttmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bhitungtotmakanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(cmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tnamamakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thargamakan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tbelimakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ttmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bhitungtotmakanan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panelMenu);
        panelMenu.setBounds(20, 160, 710, 260);

        panelDelivery.setBackground(new java.awt.Color(204, 204, 204));

        comboLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH LAYANAN", "TAKEWAY", "DELIVERY", "MAKAN DI TEMPAT" }));
        comboLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLayananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeliveryLayout = new javax.swing.GroupLayout(panelDelivery);
        panelDelivery.setLayout(panelDeliveryLayout);
        panelDeliveryLayout.setHorizontalGroup(
            panelDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeliveryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        panelDeliveryLayout.setVerticalGroup(
            panelDeliveryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeliveryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelDelivery);
        panelDelivery.setBounds(20, 420, 340, 30);

        tarea.setColumns(20);
        tarea.setRows(5);
        jScrollPane1.setViewportView(tarea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(390, 430, 327, 200);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("HARGA LAYANAN : ");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(30, 460, 130, 16);
        getContentPane().add(hargaLayanan);
        hargaLayanan.setBounds(150, 460, 80, 22);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("TOTAL HARGA :");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(30, 490, 130, 16);
        getContentPane().add(totharga);
        totharga.setBounds(150, 490, 80, 22);

        bbersih.setText("BERSIH");
        bbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbersihActionPerformed(evt);
            }
        });
        getContentPane().add(bbersih);
        bbersih.setBounds(250, 520, 90, 23);

        bselesai.setText("SELESAI");
        bselesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bselesaiActionPerformed(evt);
            }
        });
        getContentPane().add(bselesai);
        bselesai.setBounds(250, 550, 90, 23);
        getContentPane().add(totubay);
        totubay.setBounds(150, 520, 80, 22);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("UANG BAYAR :");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(30, 520, 110, 16);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("UANG KEMBALI :");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(30, 550, 120, 16);
        getContentPane().add(totukem);
        totukem.setBounds(150, 550, 80, 22);

        btotal.setText("PROSES TOTAL");
        btotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btotalActionPerformed(evt);
            }
        });
        getContentPane().add(btotal);
        btotal.setBounds(40, 580, 300, 23);

        bubay.setText("PROSES UANG BAYAR");
        bubay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubayActionPerformed(evt);
            }
        });
        getContentPane().add(bubay);
        bubay.setBounds(40, 610, 300, 23);

        bgrnn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/20240620_040124.jpg"))); // NOI18N
        getContentPane().add(bgrnn);
        bgrnn.setBounds(10, 10, 810, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BersihPanelMakanan() {
        tbelimakanan.setText("");
        ttmakanan.setText("");
        bhitungtotmakanan.setEnabled(false);

    }


    private void cmakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmakananActionPerformed
        // TODO add your handling code here:
        BersihPanelMakanan();

        String paket = cmakanan.getSelectedItem().toString();
        // memanggil fungsi set paket, lalu memasukan nilai paket yg sudah di pilih sebelum nya
        ksr.setPaket(paket);
        
        // dengan mengambil nilai dari fungsi getPaketNamaMakanan()
        tnamamakanan.setText(ksr.getPaketNamaMakanan());
        // dengan mengambil nilai dari fungsi getPaketHargaMakanan() sekaligus mengkonversi
        thargamakan.setText(Long.toString(ksr.getPaketHargaMakanan()));
        // mengaktifkan textfield pada var belimakanan
        tbelimakanan.setEnabled(true);
        
        // sselanjut nya maka saya akan menjelaskan fungsi aksi pada textfield var belimakanan

    }//GEN-LAST:event_cmakananActionPerformed


    private void bhitungtotmakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungtotmakananActionPerformed
        // TODO add your handling code here:
        // combobox jenis makanan
        if (cmakanan.getSelectedIndex() == 0) {
            System.out.println("Anda Memilih Menu '" + cmakanan.getSelectedItem().toString() + "', Paket tsb tidak tersedia");
           // dengan isi paramater nya yaitu ...
            ksr.setPaket("");
        } else {
            System.out.println("Anda Memilih Menu '" + cmakanan.getSelectedItem().toString() + "'");
            // textfield total harga makanan dengan memanggil fungsi totalHargaMakanan()
            // sekaligus mengkonversi ke tipe data string
            ttmakanan.setText(Long.toString(ksr.totalHargaMakanan()));
        }


    }//GEN-LAST:event_bhitungtotmakananActionPerformed

    private void jmineralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmineralActionPerformed
        // TODO add your handling code here:
        tjummineral.setText("");
        System.out.println("Memilih Minuman '" + jmineral.getText() + "'");
        String text = jmineral.getText();

        // ada sebuah kondisi jika checkbox di selected
        if (jmineral.isSelected()) {
            // mengaktifkan text field pada jumlah beli mineral
            tjummineral.setEnabled(true);
        } else {
            // jika checkboxnya tidak selected
            ksr.setJumlahBeliJenisMinuman(0, "AIR MINERAL");
            // menonaktifkan textfield jumlah beli mineral
            tjummineral.setEnabled(false);
        }
    }//GEN-LAST:event_jmineralActionPerformed

    private void jtehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtehActionPerformed
        System.out.println("Memilih Minuman '" + jteh.getText() + "'");

        String text = jteh.getText();
        tjumteh.setText("");
        if (jteh.isSelected()) {
            tjumteh.setEnabled(true);
        } else {
            ksr.setJumlahBeliJenisMinuman(0, "ES TEH MANIS");
            tjumteh.setEnabled(false);
        }
    }//GEN-LAST:event_jtehActionPerformed

    private void jkopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkopiActionPerformed
        // TODO add your handling code here:
        tjumkosu.setText("");
        System.out.println("Memilih Minuman '" + jkopi.getText() + "'");
        String text = jkopi.getText();

        if (jkopi.isSelected()) {
            tjumkosu.setEnabled(true);
        } else {
            ksr.setJumlahBeliJenisMinuman(0, "ES KOPI SUSU");
            tjumkosu.setEnabled(false);
        }
    }//GEN-LAST:event_jkopiActionPerformed

    private void bhitungtotminumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungtotminumanActionPerformed
        // TODO add your handling code here:]
        // text field total harga minuman dengan memanggil ...
        ttminuman.setText(Long.toString(ksr.totalHargaMinuman()));

    }//GEN-LAST:event_bhitungtotminumanActionPerformed

    private void showMessageDialog(String text) {
        JOptionPane.showMessageDialog(null, text, "INFO", JOptionPane.INFORMATION_MESSAGE);
    }

    private void tbelimakananKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbelimakananKeyReleased
        // TODO add your handling code here:
        String text = tbelimakanan.getText();

        // ada sebuah kondisi
        if (text.isEmpty() || Integer.parseInt(text) <= 0) {
            System.out.println("MINIMAL BELI LEBIH DARI 1 !!");
            // menonaktifkan button hitung total makanan nya
            bhitungtotmakanan.setEnabled(false);
            return;
        }
        System.out.println("Total Beli : " + text);

        // jika text pada var belimakanan nya tidak kosong
        // mengkonversi totalbeli nya menjadi integer
        int totalBeli = Integer.parseInt(text);
        // memanggil fungsi setJumlahBeliMakanan() dengan isi paramater nya yaitu totalBeli
        ksr.setJumlahBeliMakanan(totalBeli);
        
        // button total hitung makanan
        bhitungtotmakanan.setEnabled(true);
        
        // selanjut nya kita ke fungsi aksi button total
    }//GEN-LAST:event_tbelimakananKeyReleased

    private void tjummineralKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tjummineralKeyReleased
        // TODO add your handling code here:
        String text = tjummineral.getText();

        System.out.println(text);

        // ada kondisi text nya kosong / value text nya kurang dari 0
        if (text.isEmpty() || Integer.parseInt(text) <= 0) {
            System.out.println("MINIMAL BELI LEBIH DARI 1 !!");
            bhitungtotminuman.setEnabled(false);
            return;
        }
        System.out.println("Total Beli : " + text);

        int totalBeli = Integer.parseInt(text);
        // jika ada value text nya
        ksr.setJumlahBeliJenisMinuman(totalBeli, "AIR MINERAL");
        bhitungtotminuman.setEnabled(true);
    }//GEN-LAST:event_tjummineralKeyReleased

    private void tjumtehKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tjumtehKeyReleased
        // TODO add your handling code here:
        String text = tjumteh.getText();

        if (text.isEmpty() || Integer.parseInt(text) <= 0) {
            System.out.println("MINIMAL BELI LEBIH DARI 1 !!");
            bhitungtotminuman.setEnabled(false);
            return;
        }
        System.out.println("Total Beli : " + text);

        int totalBeli = Integer.parseInt(text);
        ksr.setJumlahBeliJenisMinuman(totalBeli, "ES TEH MANIS");
        bhitungtotminuman.setEnabled(true);
    }//GEN-LAST:event_tjumtehKeyReleased


    private void tjumkosuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tjumkosuKeyReleased
        // TODO add your handling code here:
        String text = tjumkosu.getText();

        if (text.isEmpty() || Integer.parseInt(text) <= 0) {
            System.out.println("MINIMAL BELI LEBIH DARI 1 !!");
            bhitungtotminuman.setEnabled(false);
            return;
        }
        System.out.println("Total Beli : " + text);

        int totalBeli = Integer.parseInt(text);
        ksr.setJumlahBeliJenisMinuman(totalBeli, "ES KOPI SUSU");
        bhitungtotminuman.setEnabled(true);
    }//GEN-LAST:event_tjumkosuKeyReleased

    private void comboLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLayananActionPerformed
        // TODO add your handling code here:
        // dengan layanan yg sudah di selected
        ksr.setLayananPembayaran(comboLayanan.getSelectedItem().toString());

    }//GEN-LAST:event_comboLayananActionPerformed

    private void bubayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubayActionPerformed
        // TODO add your handling code here:
        long total = ksr.totalPembayaran();

        if (total <= 0) {
            System.out.println("Upss seperti nya kamu harus mengisi orderan terlebih dahulu");
            showMessageDialog("Upss seperti nya kamu harus mengisi orderan terlebih dahulu");
            return;
        }

        long totalBayar = Long.parseLong(totubay.getText());
        // ada kondisi jika total uang pembeli lebih besar dari total pembayaran
        if (totalBayar >= total) {
            // mengubah text field total kembalian, dengan memanggil fungsi totalKembalian()
            totukem.setText(Long.toString(ksr.totalKembalian(totalBayar)));
            System.out.println("UANG CUKUP");
            showMessageDialog("Berhasil Melakukan Pembayaran");
        } else {
            System.out.println("UANG TIDAK CUKUP");
            showMessageDialog("Upss uang tidak cukup");
        }
    }//GEN-LAST:event_bubayActionPerformed

    private void bbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbersihActionPerformed
        // TODO add your handling code here:
        Bersih();
    }//GEN-LAST:event_bbersihActionPerformed

    private void bselesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bselesaiActionPerformed
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(null, "yakin mau keluar ?", "konfirmasi keluar aplikasi", JOptionPane.OK_OPTION);
        if (konfirmasi == JOptionPane.OK_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_bselesaiActionPerformed

    private void btotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btotalActionPerformed
        // TODO add your handling code here:

        // memanggil ...
        long total = ksr.totalPembayaran();
        System.out.println("Total Pembayaran " + total);

        // ada kondisi ...
        if (total <= 0) {
            System.out.println("Upss seperti nya kamu harus mengisi orderan terlebih dahulu");
            showMessageDialog("Upss seperti nya kamu harus mengisi orderan terlebih dahulu");

        } else {
            // mengaktifkan textfield total bayar
            totubay.setEnabled(true);

            // mengubah text field total harga menjadi total
            totharga.setText(Long.toString(total));
            // mengubah text field harga layanan dengan memanggil ...
            hargaLayanan.setText(Long.toString(ksr.totalHargaLayanan()));
        }
    }//GEN-LAST:event_btotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Warung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Warung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbersih;
    private javax.swing.JLabel bgrnn;
    private javax.swing.JButton bhitungtotmakanan;
    private javax.swing.JButton bhitungtotminuman;
    private javax.swing.JButton bselesai;
    private javax.swing.JButton btotal;
    private javax.swing.JButton bubay;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmakanan;
    private javax.swing.JComboBox<String> comboLayanan;
    private javax.swing.JTextField hargaLayanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jkopi;
    private javax.swing.JCheckBox jmineral;
    private javax.swing.JCheckBox jteh;
    private javax.swing.JPanel panelDelivery;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTextArea tarea;
    private javax.swing.JTextField tbelimakanan;
    private javax.swing.JTextField thargamakan;
    private javax.swing.JTextField tharjmlhkopi;
    private javax.swing.JTextField tharjmlhmin;
    private javax.swing.JTextField tharjmlhteh;
    private javax.swing.JTextField tjumkosu;
    private javax.swing.JTextField tjummineral;
    private javax.swing.JTextField tjumteh;
    private javax.swing.JTextField tnamamakanan;
    private javax.swing.JTextField totharga;
    private javax.swing.JTextField totubay;
    private javax.swing.JTextField totukem;
    private javax.swing.JTextField ttmakanan;
    private javax.swing.JTextField ttminuman;
    // End of variables declaration//GEN-END:variables
}
